### ISSUE TITLE
when will the blur effect appear?

### ISSUE THREAD

**Issue by VERON0990** [Open4Es/Open4Es-Shader-Android#10]

**Comment by ENDERMANYK** [comment]
GL4ES  is very limited, so maybe is not possible

**Comment by GabudPeople** [comment]
> _No description provided._

Using Motion Blur On GL4ES Is So Laggy :|

**Comment by VERON0990** [comment]
> GL4ES is very limited, so maybe is not possible

I mean blurring on the shadows as they are too charcoal

**Comment by AjGamingPHOfficial** [comment]
69 years
