### ISSUE TITLE
Rewrite it for vgpu

### ISSUE THREAD

**Issue by LegacyGamerHD** [Open4Es/Open4Es-Shader-Android#101]
With vgpu this is possible 

![Screenshot_20210822-100701](https://user-images.githubusercontent.com/25864932/130347388-a56f2f4c-a83e-4670-8b05-25b0fa0b0c89.png)
![Screenshot_20210822-100639](https://user-images.githubusercontent.com/25864932/130347389-abb22bc9-ee93-4304-9cac-b3048a24ef64.png)
![Screenshot_20210822-100308](https://user-images.githubusercontent.com/25864932/130347390-ec88d949-0a71-4eba-9b47-935c2c85784c.png)
![Screenshot_20210822-100257](https://user-images.githubusercontent.com/25864932/130347392-b461c0a1-8bfd-4c6e-8594-c7163281f58e.png)

Open source shader is here https://github.com/luo9674/VGPU/blob/main/shaders/SSR%20TEST%20v2.zip

Note it needs vgpu it isn't possible on gl4es

**Comment by Ivyjunsy** [comment]
Did you do this???
This is so cool.... 
How did you even manage it???... 
:) :D

**Comment by LegacyGamerHD** [comment]
> Did you do this???
> This is so cool....
> How did you even manage it???...
> :) :D

shaders are not mine but from maker of vgpu

**Comment by BurstingCreeper** [comment]
@LegacyGamerHD  me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental

**Comment by LegacyGamerHD** [comment]
> @LegacyGamerHD me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental

Then use it as a base

**Comment by BurstingCreeper** [comment]
> 
> 
> > @LegacyGamerHD me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental
> 
> Then use it as a base

ok trying to add skybox

**Comment by LegacyGamerHD** [comment]
> > > @LegacyGamerHD me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental
> > 
> > 
> > Then use it as a base
> 
> ok trying to add skybox

yk it has reflections

**Comment by LegacyGamerHD** [comment]
the readme said this;

Welcome to this shader.
The shader is open source, allowed to be reworked or added to new works.

It can run on vgpu 1.3.4-1.4, zink, PC.

It contains two main effects: shadow and water.
By default, shadows use multisampling (3 times) soft shadows.
Water effects include simple 3D screen space reflections, fake sky reflections, simple noise waves (you can add custom more complex noise to achieve more realistic waves).

Not Added Bloom.

**Comment by LegacyGamerHD** [comment]
> > > @LegacyGamerHD me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental
> > 
> > 
> > Then use it as a base
> 
> ok trying to add skybox

i have seen it before the experimental and rn it just basic with no reflection and it isnt a nice shaders in my eyes

**Comment by BurstingCreeper** [comment]
> 
> 
> > > > @LegacyGamerHD me and endermanyk trying to make one for vgpu https://github.com/Open4Es/Open4Es-Exprimental
> > > 
> > > 
> > > Then use it as a base
> > 
> > 
> > ok trying to add skybox
> 
> i have seen it before the experimental and rn it just basic with no reflection and it isnt a nice shaders in my eyes

endermanyk exe has stopped working

**Comment by BurstingCreeper** [comment]
bruh
