### ISSUE TITLE
(suggestion) can you make Open4Es shader Beta6 not use vgpu

### ISSUE THREAD

**Issue by SteveAlexM** [Open4Es/Open4Es-Shader-Android#102]
I can't use the vgpu renderer on my phone, that's why I made this suggestion.

**Comment by BurstingCreeper** [comment]
@SteveAlexM Its not possible now for beta 6. And gl4es has so less api than vgpu open4es can't go more than its limit for gl4es. thats why beta 6 is for vgpu

**Comment by SteveAlexM** [comment]
Ok thank you
