### ISSUE TITLE
how do i get VGPU please help

### ISSUE THREAD

**Issue by UnknownMcUser** [Open4Es/Open4Es-Shader-Android#103]

**Comment by ENDERMANYK** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1162210673

**Comment by Danielgamer90** [comment]
> https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1162210673

I have a question, do not you need to put JVM arguments?

**Comment by BurstingCreeper** [comment]
select vgpu from renderer in pojav
