### ISSUE TITLE
Shader is not working on my mid-range phone OPPO A12e.

### ISSUE THREAD

**Issue by LANCECRAFT1104** [Open4Es/Open4Es-Shader-Android#11]
The shader is not working on my mid-range phone. The shadows, sun flare etc...are not working, only the sun is working.

Phone specs:
Chipset/CPU: Qualcomm SDM450 Octa-Core 1.8 GHz Cortex-A53

GPU: Andreno 506/OpenGL ES 3.1+

is there a problem on my specs?

**Comment by LANCECRAFT1104** [comment]
This shader needs more updates. Plz update and update this shader so that this shader will run on all phones.

**Comment by LANCECRAFT1104** [comment]
I see "Error Invalid Program" on the chat.

**Comment by ENDERMANYK** [comment]
Give a screenshot your problem and launcher version

**Comment by LANCECRAFT1104** [comment]
> Give a screenshot your problem and launcher version

Okay

**Comment by LANCECRAFT1104** [comment]
![Screenshot_2021-04-04-20-37-59-16](https://user-images.githubusercontent.com/75970303/113508980-be403500-9585-11eb-8be3-239e0f754a92.png)

Version 3.3.1.1_rel_20210403

**Comment by LANCECRAFT1104** [comment]
I am a Snapdragon

**Comment by LANCECRAFT1104** [comment]
I am using bare bones texture pack

**Comment by LANCECRAFT1104** [comment]
> ![Screenshot_2021-04-04-20-37-59-16](https://user-images.githubusercontent.com/75970303/113508980-be403500-9585-11eb-8be3-239e0f754a92.png)
> 
> Version 3.3.1.1_rel_20210403

This is not a PC I only hide my controls.

**Comment by ENDERMANYK** [comment]
Switch your launcher version to Google play store version

**Comment by LANCECRAFT1104** [comment]
> Switch your launcher version to Google play store version

If I install play store ver the shader will work 100%?

**Comment by LANCECRAFT1104** [comment]
Thank you
