### ISSUE TITLE
I can see vanilla line in water plss fix 

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#110]
The water shader I can see vanilla line in water shader

**Comment by BurstingCreeper** [comment]
@kedrick021 can u send me a screenshot?

**Comment by kedrick021** [comment]
> @kedrick021 can u send me a screenshot?

![Uploading Screenshot_2021-09-10-17-56-30-540_org.videolan.vlc.jpg…]()

**Comment by kedrick021** [comment]
![Screenshot_2021-09-10-17-56-30-540_org videolan vlc](https://user-images.githubusercontent.com/76839710/132836547-a5e4eddf-7223-47a5-a96d-5cd9b022303f.jpg)

**Comment by kedrick021** [comment]
> @kedrick021 can u send me a screenshot?

![Screenshot_2021-09-10-17-56-30-540_org videolan vlc](https://user-images.githubusercontent.com/76839710/132836597-f4e4f943-4651-4c8c-baa5-b0b82628f360.jpg)

**Comment by BurstingCreeper** [comment]
do u really think this is a bug? ~~bruh~~

**Comment by BurstingCreeper** [comment]
the water is made like enchanted default shaders

**Comment by kedrick021** [comment]
That open4es v6

**Comment by kedrick021** [comment]
> the water is made like enchanted default shaders

That open4es v6

**Comment by BurstingCreeper** [comment]
@kedrick021 the water is made like enchanted default in open 4es eta 6. ENDERMANYK didn't added any noise in water

**Comment by kedrick021** [comment]
> @kedrick021 the water is made like enchanted default in open 4es eta 6. ENDERMANYK didn't added any noise in water

I know I just saying this him
