### ISSUE TITLE
There is a Secret Feature in Beta 6

### ISSUE THREAD

**Issue by romeoga05** [Open4Es/Open4Es-Shader-Android#112]
Depth Of Field

![Screenshot_2021-08-30-14-09-21-386_com miui videoplayer](https://user-images.githubusercontent.com/78824521/132093501-b4ceb66b-2c0f-4412-949c-d006435c34fb.jpg)

**Comment by romeoga05** [comment]
![IMG_20210904_135352](https://user-images.githubusercontent.com/78824521/132093552-01a66804-d824-49c9-9f01-2420dec722eb.jpg)

But i don't Say how to turn It on

**Comment by BurstingCreeper** [comment]
@ENDERMANYK can help i guess

**Comment by BurstingCreeper** [comment]
he added it

**Comment by romeoga05** [comment]
Ok

**Comment by kedrick021** [comment]
Shup don't make false information

**Comment by BurstingCreeper** [comment]
@kedrick021 what?
whats false?

**Comment by BurstingCreeper** [comment]
@kedrick021 endermanyk added depth of field. He is dev of open4es and he alsoo told me before adding dof
