### ISSUE TITLE
suggestion for shader style

### ISSUE THREAD

**Issue by Koijiro2** [Open4Es/Open4Es-Shader-Android#114]
can you make a open4es shader look like this?
make a sky like this too plsss

video link
100 video but he is using this super vibrant shader I really like the shader.

https://youtu.be/nK41Xo2aAaI

(or can you make ashader like that)

**Comment by BurstingCreeper** [comment]
@Koijiro2 thats not possible in vgpu it has still limitation.if u wan't more freatures then open4es will need zink. and many phone dooesn't support zink

**Comment by Danielgamer90** [comment]
> @Koijiro2 thats not possible in vgpu it has still limitation.if u wan't more freatures then open4es will need zink. and many phone dooesn't support zink

There is a way to use Zink on a phone that is not supported

**Comment by Danielgamer90** [comment]
> > @Koijiro2 thats not possible in vgpu it has still limitation.if u wan't more freatures then open4es will need zink. and many phone dooesn't support zink
> 
> There is a way to use Zink on a phone that is not supported

https://youtu.be/uHYahhoCkEc

**Comment by Danielgamer90** [comment]
> > > @Koijiro2 thats not possible in vgpu it has still limitation.if u wan't more freatures then open4es will need zink. and many phone dooesn't support zink
> > 
> > 
> > There is a way to use Zink on a phone that is not supported
> 
> https://youtu.be/uHYahhoCkEc

I don't know if it will work for everyone but mine it worked.

**Comment by Danielgamer90** [comment]
![Uploading Screenshot_20210913-161233.jpg…]()

**Comment by BurstingCreeper** [comment]
@Danielgamer90 its open4es not bsl shader

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
> @Danielgamer90 its open4es not bsl shader

It's not OPEN4ES

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.24.52.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
> > @ Danielgamer90 seu open4es e não bsl shader
> 
> Não é OPEN4ES

![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.11.39.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-13_11.48.05.png…]()

**Comment by Danielgamer90** [comment]
![Uploading 2021-09-14_08.24.52.png…]()
