### ISSUE TITLE
Weird discovery?

### ISSUE THREAD

**Issue by UnknownMcUserbackupaccount** [Open4Es/Open4Es-Shader-Android#115]
I got the new vgpu as i am a very great fan of open4es shader but when i opened the game and applied it it didn't show any of the new thing's that were showed in the change log and i looked like normal minecraft but this is either because my phone is a low end device

**Comment by BurstingCreeper** [comment]
@UnknownMcUserbackupaccount send a screenshot

**Comment by UnknownMcUserbackupaccount** [comment]
> @UnknownMcUserbackupaccount send a screenshot

![Screenshot_20210913-194649](https://user-images.githubusercontent.com/90603825/133175752-0107eb92-7640-452e-9d7c-66fc1b59abe1.png)

**Comment by BurstingCreeper** [comment]
mali gpu?

**Comment by UnknownMcUserbackupaccount** [comment]
So i did the thing's you said but it didn't fix the issue
![Screenshot_20210915-044545](https://user-images.githubusercontent.com/90603825/133411761-477e07e7-2e21-45da-801f-573536184657.png)
![Screenshot_20210915-044530](https://user-images.githubusercontent.com/90603825/133411780-c2000c5d-5e69-47ff-acaf-9068109103be.png)
![Uploading Screenshot_20210915-044519.png…]()

**Comment by BurstingCreeper** [comment]
hmm send latest log txt inpojavlauncer iles try to find it and send
and whats ur phone spec?

**Comment by ENDERMANYK** [comment]
~~seems the issue is the Mali GPU or idk~~

**Comment by BurstingCreeper** [comment]
ya mali gpu is harmful for open4es XD

**Comment by UnknownMcUserbackupaccount** [comment]
Oh :(
