### ISSUE TITLE
shader vgpu not working on my phone

### ISSUE THREAD

**Issue by SteveAlexM** [Open4Es/Open4Es-Shader-Android#116]
on my cellphone, there are many errors in the vgpu shader, please fix it. For example : error gbuffers_water.vsh

**Comment by BurstingCreeper** [comment]
phone spec?

**Comment by BurstingCreeper** [comment]
@SteveAlexM u need snapdragon prossecor to get no bugs

**Comment by SteveAlexM** [comment]
if it's a bug it doesn't matter, but the shader is an error, the mediatek helio p22 processor, if another cellphone (the specifications are the same as mine) can load this shader with vgpu..

**Comment by SteveAlexM** [comment]
Ram: 3gb Rom: 32gb on other cellphones (the specifications are the same) even though Ram is 2gb, why do you think?

**Comment by SteveAlexM** [comment]
Ram: 3gb Rom: 32gb on other cell phones (the specifications are the same) even though Ram is 2gb, why do you think?

**Comment by SteveAlexM** [comment]
do i need a Snapdragon processor or mediatek helio g80 and above?

**Comment by SteveAlexM** [comment]
My device 🔽
Vivo y12
Ram:3GB
Rom:32GB
Processor: mediatek helio p22
GPU: Power VR Rogue GE8320
Android version:9
AARCH 64

**Comment by BurstingCreeper** [comment]
@SteveAlexM can u send me a pic off the bug?

**Comment by SteveAlexM** [comment]
Ok

**Comment by SteveAlexM** [comment]
![IMG_20210914_211157](https://user-images.githubusercontent.com/83632207/133273976-2f7ab8f6-5807-4445-9d80-ab84d50bc2ba.jpg)
sometimes it's like this or sometimes it's a water error and its final

**Comment by SteveAlexM** [comment]
![IMG_20210914_211352](https://user-images.githubusercontent.com/83632207/133274131-914d774b-c80b-4b76-a984-afa780296331.jpg)
sometimes it's like this or sometimes it's a water error and its final

**Comment by BurstingCreeper** [comment]
@SteveAlexM can u send the log file at games>Pojavlauncher>.minecraft>log>latest log.txt

**Comment by SteveAlexM** [comment]
@BurstingCreeper  ok a moment

**Comment by BurstingCreeper** [comment]
bruh thats weird shadow and water not working

**Comment by BurstingCreeper** [comment]
have u selected vgpu renderer on pojavlauncher options?

**Comment by SteveAlexM** [comment]
@BurstingCreeper  yes

**Comment by SteveAlexM** [comment]
By the way, on my friend's cellphone, I also have the same error as my friend's cellphone device🔽 vivo y20 
Ram: 4gb 
Rom: 64gb 
processor: mediatek helio p35 
gpu: Power VR Rogue 
AARCH64

**Comment by SteveAlexM** [comment]
By the way, on my friend's cellphone, I also have the same error as my friend's cellphone device vivo y20 
Ram: 4gb 
Rom: 64gb 
processor: mediatek helio p35 
gpu: Power VR Rogue 
AARCH64

**Comment by SteveAlexM** [comment]
by the way on my friend's cellphone, there is also the same error as mine.  my friend's hp device vivo y20 
Ram:4gb 
Rom:64gb 
processor: mediatek helio p35 
gpu: Power VR Rogue 
AARCH64
sorry I forgot to ask for the latestlog.txt

**Comment by SteveAlexM** [comment]
and the picture of the bug

**Comment by SteveAlexM** [comment]
but basically the bug is the same as mine

**Comment by ENDERMANYK** [comment]
~~VGPU was developed on adreno GPU , it's known it will have render problem or other GPU~~
