### ISSUE TITLE
Enhanced Default Open4ES

### ISSUE THREAD

**Issue by Igao3Mil** [Open4Es/Open4Es-Shader-Android#120]
It would be cool if you could make a version of the shaders with only the shadows, no post processing, reflections or anything like that, only shadows.

**Comment by zigordlc** [comment]
I have some filters on top, maybe your device doesn't support them.

**Comment by Birbs-are-cute** [comment]
@zigordlc thats called tonemapping.anyway lemme think about a better default version

**Comment by Birbs-are-cute** [comment]
@zigordlc checkout releases there is a version open4es improved default
