### ISSUE TITLE
Detailed installation/setup tutorial needed

### ISSUE THREAD

**Issue by TehDomic** [Open4Es/Open4Es-Shader-Android#125]
I have a Snapdragon 845 phone and there is no obvious tutorial for new users like me who come here to try and install these shaders.
I can't figure out which MC versions these work on, which PojavLauncher renderer can/should be used, etc etc, there just is too little information to go on. I have installed Optifine but the shaders don't work across several configurations I try out.

**Comment by ENDERMANYK** [comment]
Below the readme there is a installation tutorial ![Screenshot_2021-11-18-17-04-54-75_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/64646658/142384681-5a92e688-a067-4196-8464-a3726ef5f9e4.jpg)

**Comment by TehDomic** [comment]
The video this Android image link links to is 9 seconds long and the video description does not have any instructions in it.

It must be the wrong video or something. Please take a look at this video to confirm.

**Comment by ENDERMANYK** [comment]
hmm, seems the original creator remove it, but i can still tell you something. For using it, you need select GL4ES or VGPU render in the launcher, for the shader working, you need put the zip file in the shaderpacks file which generated by Optifine, it usually located in sdcard/Android/data/net.pojavlauncher.debug/.minecraft. Then launch the game, go into the settings-->video settings and find the shader file. Select to enable it

**Comment by Birbs-are-cute** [comment]
hmmm looks like @TehDomic needs help XD 
https://youtu.be/wj8396AJsAM
