### ISSUE TITLE
 Strange Shadows

### ISSUE THREAD

**Issue by Melscers** [Open4Es/Open4Es-Shader-Android#127]
What is this? I have trouble with shadows. This is clearly visible while running. How do I fix this?
![Screenshot_2021-12-15-15-06-19-423_net kdt pojavlaunch](https://user-images.githubusercontent.com/91048442/146148807-6bfb8726-56ec-477a-99a6-8465a7f784e4.jpg)
![Screenshot_2021-12-15-15-18-30-180_net kdt pojavlaunch](https://user-images.githubusercontent.com/91048442/146150843-373a3f5e-c2f8-4731-b28d-130f382d4a72.jpg)
![Screenshot_2021-12-15-15-18-22-081_net kdt pojavlaunch](https://user-images.githubusercontent.com/91048442/146150855-7587da61-3def-416a-bcfd-81ba4efd021b.jpg)

**Comment by LightestMC** [comment]
enable anti-aliasing in the shader settings

**Comment by Birbs-are-cute** [comment]
@Melscers Shadow pcf only works in snapdragon prossecors
