### ISSUE TITLE
[Question] Is This Normal?

### ISSUE THREAD

**Issue by GabudPeople** [Open4Es/Open4Es-Shader-Android#13]
![Screenshot_2021-04-05-10-17-02-18_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79894293/113533730-d735fe00-95f8-11eb-9386-7a4b3db6b29a.jpg)

The Error Thingy

Mediatek Helio G35
PowerVR Rogue GE8320

**Comment by StwfGT** [comment]
But i got error while in game it says invalid enum "final"
But how to fix it?

**Comment by KylePlayX** [comment]
Just ignore it :)

**Comment by ENDERMANYK** [comment]
it's normal to get bugs if you are not on Snapdragon device
