### ISSUE TITLE
Shader Black Sky Error

### ISSUE THREAD

**Issue by Gabbyph12** [Open4Es/Open4Es-Shader-Android#130]
How it's shader error

**Comment by ENDERMANYK** [comment]
we need more information since this shader have a lot of versions and pojavlauncher have a lot of renders

**Comment by Gabbyph12** [comment]
Renderer Vgpu Minecraft 1.12.2 Pojav launcher Play store Version

**Comment by ENDERMANYK** [comment]
i have a feeling you disable the sky in the optifine settings

**Comment by Gabbyph12** [comment]
It's enabled but only working on Zink But Zink Is laggy
