### ISSUE TITLE
Shadow line how to fix on Mali gpu?

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#131]

**Comment by Ariya1388h** [comment]
My phone is mali too and I have line whadow problem too

**Comment by JhoncelSMP** [comment]
I have shadow line and i don't know how to fix it?

**Comment by Birbs-are-cute** [comment]
@kedrick021 @Ariya1388h @JhoncelSMP Its no possible to fix that bug currently
