### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by lehoanduphong** [Open4Es/Open4Es-Shader-Android#135]
please help: the shader is nice, but it has an annoying black stripe so how to fix it

**Comment by Birbs-are-cute** [comment]
@lehoanduphong can u send a screenshot please.
Also yell ur device specs and which version of shader  u using?

**Comment by lehoanduphong** [comment]
> 

![Screenshot_20220506-121503_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/167071519-367bdca0-79e0-4180-b85b-7d30a2f9d59e.jpg)
![Screenshot_20220506-121453_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/167071524-12863bfe-518a-459e-a83a-4502f03d6ebd.jpg)
![Screenshot_20220506-121326_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/167071532-7d57dcca-0215-497f-aea2-6c0737cf1d1e.jpg)
![Screenshot_20220506-121312_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103303530/167071536-b6dfd5cf-89fb-43a9-81cb-91cf48ff4494.jpg)
![Screenshot_20220506-121609_CPU-Z](https://user-images.githubusercontent.com/103303530/167071539-f3604edf-1cf9-4267-bc33-44210b4ce3eb.jpg)
![Screenshot_20220506-121614_CPU-Z](https://user-images.githubusercontent.com/103303530/167071541-f408ccb5-cbc3-42ae-b861-0a084ba3852e.jpg)

**Comment by ENDERMANYK** [comment]
thats a out of support version, just use the latest version

**Comment by Birbs-are-cute** [comment]
@lehoanduphong That is the problem u have exynoss prossecor also use the latest versions of vgpu if ur phone supports as Endermanyk said like later than open4es beta 6

**Comment by lehoanduphong** [comment]
> @lehoanduphong That is the problem u have exynoss prossecor also use the latest versions of vgpu if ur phone supports as Endermanyk said like later than open4es beta 6

I do not understand

**Comment by Birbs-are-cute** [comment]
@lehoanduphong U need a phone with snapdragon prossecor. Or just play with vgpu renderer and open4es beta 7

**Comment by lehoanduphong** [comment]
> @lehoanduphongBạn cần một chiếc điện thoại với snapdragon prossecor. Hoặc chỉ chơi với trình kết xuất vgpu và open4es beta 7

Vậy có giải pháp nào khác không

**Comment by Birbs-are-cute** [comment]
@lehoanduphong No i guess

**Comment by kedrick022** [comment]
This shader is same bug on Mali gpu have shadow line

**Comment by Birbs-are-cute** [comment]
@kedrick022 this bug can't be fixed :(

**Comment by kedrick022** [comment]
This shader can play on VirGL Renderer? can you make this shader works on VirGL only VirGL can render shadow without shadow line in Mali gpu

**Comment by Birbs-are-cute** [comment]
I can't but i can try in future u can also check zink if it works

**Comment by kedrick022** [comment]
Zink not working and laggg
