### ISSUE TITLE
No open4es shader for virgl render?

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#136]

**Comment by Birbs-are-cute** [comment]
Yup

**Comment by kedrick021** [comment]
> Yup

Why?

**Comment by Birbs-are-cute** [comment]
@kedrick021 devloper is busy with yssbe render dragon edition and some other stuff

**Comment by ENDERMANYK** [comment]
virgl already support PC shaders, there is no point to make a shader that support virgl only
