### ISSUE TITLE
1.18 is crashing with this pls help

### ISSUE THREAD

**Issue by Pojavhelppls** [Open4Es/Open4Es-Shader-Android#137]
Plss

**Comment by Birbs-are-cute** [comment]
@Pojavhelppls for ur kind info-this shader isn't made for 1.18

**Comment by Pojavhelppls** [comment]
Is there any open4es Shader for 1.18

**Comment by Birbs-are-cute** [comment]
@Pojavhelppls no.Cause all open4es versions are written in glsl 120 code and 1.18 needs glsl 150

**Comment by Pojavhelppls** [comment]
Pls make a shader for 1.18

**Comment by Birbs-are-cute** [comment]
I don't know glsl 150.The founder knows but he is busy with yssbe render dragon shader

**Comment by Birbs-are-cute** [comment]
I don't know glsl 150.The founder knows but he is busy with yssbe render dragon shader

**Comment by Pojavhelppls** [comment]
What if we edit GLS code to 150

**Comment by Birbs-are-cute** [comment]
@Pojavhelppls go ahead if u know glsl coding language and don't forget to give credit of the developers

**Comment by Pojavhelppls** [comment]
Ok u can close this request

**Comment by Birbs-are-cute** [comment]
Done!
