### ISSUE TITLE
Not working on Adreno + Snapdragon 

### ISSUE THREAD

**Issue by Sookablyad** [Open4Es/Open4Es-Shader-Android#139]
Any shader except ultra lite doesn't work
CPU: Snapdragon 680
GPU: Adreno 610
6 GB RAM

Everything looks like this
![Screenshot_20221231-235652_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/87292060/210148476-2b16d3c3-54d5-43ed-bb79-35fdd65dd9ac.jpg)

**Comment by Sookablyad** [comment]
Latest version from Play Market

**Comment by ENDERMANYK** [comment]
may i know which render you are using?

**Comment by Sookablyad** [comment]
Holy gl4es

**Comment by ENDERMANYK** [comment]
and your game version?

**Comment by Sookablyad** [comment]
1.19.2

**Comment by ENDERMANYK** [comment]
Open4Es doesnt support 1.17+ at this time, need more time to solve thsi

**Comment by Pinecone6442** [comment]
> Open4Es doesnt support 1.17+ at this time, need more time to solve this

it does on pc (mostly)
