### ISSUE TITLE
Waving water suggestion

### ISSUE THREAD

**Issue by LANCECRAFT1104** [Open4Es/Open4Es-Shader-Android#14]
Add water waving.

**Comment by ENDERMANYK** [comment]
do you want to lag in your phone?

**Comment by LANCECRAFT1104** [comment]
> do you want to lag in your phone?

No

**Comment by LANCECRAFT1104** [comment]
> do you want to lag in your phone?

Wayer waving cause a lag?

**Comment by ENDERMANYK** [comment]
> > do you want to lag in your phone?
> 
> Water waving cause a lag?

every moving object can cause lag

**Comment by LANCECRAFT1104** [comment]
> > > do you want to lag in your phone?
> > 
> > 
> > Water waving cause a lag?
> 
> every moving object can cause lag

Make water waves so slow so that it will not lag.

**Comment by ENDERMANYK** [comment]
> > > > do you want to lag in your phone?
> > > 
> > > 
> > > Water waving cause a lag?
> > 
> > 
> > every moving object can cause lag
> 
> Make water waves so slow so that it will not lag.

not everyone have the same phone as you some people only have 450 device and we need to make them playable

**Comment by LANCECRAFT1104** [comment]
> > > > > do you want to lag in your phone?
> > > > 
> > > > 
> > > > Water waving cause a lag?
> > > 
> > > 
> > > every moving object can cause lag
> > 
> > 
> > Make water waves so slow so that it will not lag.
> 
> not everyone have the same phone as you some people only have 450 device and we need to make them playable

Oh come on. Add water waving settings you can turn it off if you get lag on water.

**Comment by LANCECRAFT1104** [comment]
Add settings so that we can turn off some laggy features you know that? Example i get laggy on water waving what should I do I will go to shader settings and turn off water waving feature.
