### ISSUE TITLE
Not work on 1.19.2 optifine 

### ISSUE THREAD

**Issue by Anonymous1231-dev** [Open4Es/Open4Es-Shader-Android#145]
>Attention : shader is for holy gl4es from 1.7.10(partly) - 1.19.3 running on Optifine, when using the shader make sure run the correct version that suit your device and Minecraft version

But just not work on 1.19.2 

![IMG_20230220_163231.jpg](https://user-images.githubusercontent.com/87801676/220053330-98b0b3a9-af46-4bf6-b8ae-5a4963b77da5.jpg)

**Comment by ENDERMANYK** [comment]
send the log then

**Comment by yoni13** [comment]
[Logs](https://pastebin.com/NmFELMvf)
