### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by StwfGT** [Open4Es/Open4Es-Shader-Android#15]
![Screenshot_2021-04-05-13-56-10-703_net kdt pojavlaunch](https://user-images.githubusercontent.com/76163976/113542609-39056080-9617-11eb-9f8b-02709db1be18.jpg)
How to fix that? (Im using Open4Es SEUS)

My Device Is
MediaTek Helio P35
PowerVR Rogue GE8320

**Comment by CupuGamingStudio** [comment]
Its Will be fixed soon

**Comment by CupuGamingStudio** [comment]
![Uploading Screenshot_2021-04-06-15-25-41-60_bab8561a5f94f0a53956d8cbbeaad774.jpg…]()
