### ISSUE TITLE
My Device Doesn't Get The Atmospheric Color

### ISSUE THREAD

**Issue by GabudPeople** [Open4Es/Open4Es-Shader-Android#16]
My Device Is Power VR Rogue GE8320
Helio G35
![Screenshot_2021-04-05-17-13-02-03_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/79894293/113576343-9b775480-9649-11eb-9f29-b18e2c3bc510.jpg)
it's Chocoapic Versuon But Not Get The Orange Atmospheric

**Comment by ENDERMANYK** [comment]
known issue if you are not on Snapdragon device
