### ISSUE TITLE
very good project

### ISSUE THREAD

**Issue by Minecrafterr1244** [Open4Es/Open4Es-Shader-Android#17]
It is very good that it can be played with shaders on android, it lacks some bug fixes, it is quite good, although I never get it to go to a stable 60 fps I always go to 30 to 45 fps but it is quite playable Thank you for this great project.

**Comment by ENDERMANYK** [comment]
blame ptitSeb for his lack OpenGL extensions to fix the shader，for the low FPS buy a new phone
