### ISSUE TITLE
Pls add some feature

### ISSUE THREAD

**Issue by AzarinMC** [Open4Es/Open4Es-Shader-Android#19]
Water Reflection

Better lensflare

Waving train

Thank you!!!🙏😀

**Comment by ENDERMANYK** [comment]
Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it

**Comment by LANCECRAFT1104** [comment]
https://github.com/Open4Es/Open4Es-Shader-Android/issues/14

**Comment by LANCECRAFT1104** [comment]
> Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it

Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.

**Comment by ENDERMANYK** [comment]
> > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> 
> Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.

See my second sentence "not everything is available on it"

**Comment by AzarinMC** [comment]
> > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > 
> > 
> > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> 
> See my second sentence "not everything is available on it"

But pls add water Reflection

**Comment by ENDERMANYK** [comment]
> > > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > > 
> > > 
> > > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> > 
> > 
> > See my second sentence "not everything is available on it"
> 
> But pls add water Reflection

GL4ES doesn't have the ability to ADD WATER REFLECTION

**Comment by ENDERMANYK** [comment]
> > > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > > 
> > > 
> > > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> > 
> > 
> > See my second sentence "not everything is available on it"
> 
> But pls add water Reflection

if you want water reflection, switch to zink build in Pojavlauncher and apply normal PC shader

**Comment by AzarinMC** [comment]
> > > > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > > > 
> > > > 
> > > > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> > > 
> > > 
> > > See my second sentence "not everything is available on it"
> > 
> > 
> > But pls add water Reflection
> 
> if you want water reflection, switch to zink build in Pojavlauncher and apply normal PC shader

How to switch that

**Comment by ENDERMANYK** [comment]
> > > > > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > > > > 
> > > > > 
> > > > > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> > > > 
> > > > 
> > > > See my second sentence "not everything is available on it"
> > > 
> > > 
> > > But pls add water Reflection
> > 
> > 
> > if you want water reflection, switch to zink build in Pojavlauncher and apply normal PC shader
> 
> How to switch that

ask that in Pojavlauncher GitHub instead of there, just a mention: if your device doesn't support vulkan you will not able to use zink

**Comment by AzarinMC** [comment]
> > > > > > > Do you think your phone can handle this? Second GL4ES is very limited, not everything is available on it
> > > > > > 
> > > > > > 
> > > > > > Oh come on! Add settings so that we can turn off some laggy features you know that? Example: I get laggy on water waving what should I do, I will go to shader settings and turn off water waving feature.
> > > > > 
> > > > > 
> > > > > See my second sentence "not everything is available on it"
> > > > 
> > > > 
> > > > But pls add water Reflection
> > > 
> > > 
> > > if you want water reflection, switch to zink build in Pojavlauncher and apply normal PC shader
> > 
> > 
> > How to switch that
> 
> ask that in Pojavlauncher GitHub instead of there, just a mention: if your device doesn't support vulkan you will not able to use zink

Yes iam using android 10 ITS support vulkan
