### ISSUE TITLE
can it run on pc?

### ISSUE THREAD

**Issue by demonite87x** [Open4Es/Open4Es-Shader-Android#2]
i dont know if it can run on pc because i really need a shader that can run on intel graphics, but if it can that would be very epic

**Comment by Google61** [comment]
Your driver has to support at least GL 2.1 specification.
Also, all more-or-less modern Intel CPUs support GL 4.x, meaning you should be able to run every other shader (based on performance impact, of course).
See here for details https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

**Comment by ShulkerSakura** [comment]
Yes! Iti is can run on pc!

**Comment by LANCECRAFT1104** [comment]
> i dont know if it can run on pc because i really need a shader that can run on intel graphics, but if it can that would be very epic

If you use PC this shader will run 60 FPS
