### ISSUE TITLE
When i use the Shaders, this is what happened

### ISSUE THREAD

**Issue by CupuGamingStudio** [Open4Es/Open4Es-Shader-Android#20]
![Screenshot_2021-04-06-11-36-01-01_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/81964661/113670534-72a19e80-96df-11eb-9ef7-b78deafc8ca9.jpg

**Comment by ZhakiThePro** [comment]
> ![Screenshot_2021-04-06-11-36-01-01_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/81964661/113670534-72a19e80-96df-11eb-9ef7-b78deafc8ca9.jpg

Looks like crash

**Comment by KylePlayX** [comment]
Re apply the shaders , if it didnt work your device is the problem

**Comment by CupuGamingStudio** [comment]
> Re apply the shaders , if it didnt work your device is the problem
Still same

**Comment by CupuGamingStudio** [comment]
Not work

**Comment by CupuGamingStudio** [comment]
![Screenshot_2021-04-06-15-10-13-67_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/81964661/113680821-7a674000-96eb-11eb-99d1-e8a1af857fbf.jpg

**Comment by KylePlayX** [comment]
hmm you change ur pojavlauncher settings
Give ur specs of ur phone

**Comment by CupuGamingStudio** [comment]
> hmm you change ur pojavlauncher settings
> Give ur specs of ur phone

My phone is Mediatek

**Comment by ENDERMANYK** [comment]
![Screenshot_2021-04-06-19-00-55-24_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/64646658/113701225-74348c00-970a-11eb-8084-bced5d88f1df.jpg)
Read README.md
