### ISSUE TITLE
the shaders not working properly 

### ISSUE THREAD

**Issue by ArnabGamerz** [Open4Es/Open4Es-Shader-Android#23]
the shaders dont work properly like there is no lighting 
device mode 
samsung a30s
processor Samsung Exynos 7904

**Comment by ENDERMANYK** [comment]
![Screenshot_2021-04-07-07-13-39-29_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/64646658/113788975-cf996500-9770-11eb-8522-0604a19f46d2.jpg)
Read README.md
