### ISSUE TITLE
Shadow Issue and Color doesn't change

### ISSUE THREAD

**Issue by CyClone3003** [Open4Es/Open4Es-Shader-Android#24]
![Screenshot_20210407-090839_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/82071208/113801068-4db23780-9782-11eb-826b-d49f1156e04c.jpg)
![Screenshot_20210407-090900_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/82071208/113801097-599df980-9782-11eb-8310-193d02b9b372.jpg)
Does anyone have the same issue? 
Is there something to do with my device?
I'm using Samsung Galaxy A51 
Exynos 9611
OpenGL ES 3.2

The color isn't the same like the screenshot, mine still vanilla color.

**Comment by ENDERMANYK** [comment]
![Screenshot_2021-04-07-07-13-39-29_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/64646658/113802491-6a07a180-978d-11eb-884a-8303ecb49787.jpg)
read README.md pls

**Comment by CyClone3003** [comment]
Oh, okay. I thought it'll fine. do you guys are planning to make it support on any other processor?

**Comment by ENDERMANYK** [comment]
I can't confirm about that because of GL4ES how translate the shader language but i will try

**Comment by ArnabGamerz** [comment]
U have Exynos proccessor it currently supports only Snapdragon

**Comment by ArnabGamerz** [comment]
I have the same problem like u
