### ISSUE TITLE
Can you fix this?

### ISSUE THREAD

**Issue by ZhakiThePro** [Open4Es/Open4Es-Shader-Android#26]
I asked not to be an eyesore![Screenshot_20210407_152156.jpg](https://user-images.githubusercontent.com/78971591/113826898-422c3400-97b5-11eb-854d-7f93e862fb97.jpg)

**Comment by artdeell** [comment]
Your Mediatek device  - your problem. Shader works best only on Snapdragon devices.

**Comment by ZhakiThePro** [comment]
Oh it work for MediaTek Helio G80?

**Comment by hnsmnndng** [comment]
I just want this shader to support mediatek processors too 😭 Even I envy people with snapdragon processors

**Comment by StwfGT** [comment]
> I just want this shader to support mediatek processors too 😭 Even I envy people with snapdragon processors

I have MediaTek Helio P35
But its working

**Comment by nabiloi** [comment]
> > I just want this shader to support mediatek processors too 😭 Even I envy people with snapdragon processors
> 
> I have MediaTek Helio P35
> But its working
> But i have an error it says invalid program "final"

Same

**Comment by AjGamingPHOfficial** [comment]
Lmao
