### ISSUE TITLE
When the shader will update?

### ISSUE THREAD

**Issue by CupuGamingStudio** [Open4Es/Open4Es-Shader-Android#29]
![Screenshot_2021-04-06-15-25-41-60_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/81964661/114016919-960e4a00-9895-11eb-8993-0d91c65a9a12.jpg)

**Comment by ENDERMANYK** [comment]
first everyone have life, second this is beta version, third even updated still can't fix bugs, just blame your soc factory

**Comment by jumperli** [comment]
How about let's just appreciate their hard work

**Comment by AjGamingPHOfficial** [comment]
Yee

**Comment by Danivelgamer90** [comment]
This is true because the more you update and fix the bug shader, the more beautiful and more realistic it will become

**Comment by ENDERMANYK** [comment]
use zink instead
