### ISSUE TITLE
Shading Bug

### ISSUE THREAD

**Issue by Quinxxz** [Open4Es/Open4Es-Shader-Android#30]
![Screenshot_20210409-093903_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/82218650/114181952-8126ca80-9918-11eb-89d4-4833cf5a3b35.jpg)

**Comment by Quinxxz** [comment]
My processor is an snapdragon, i dunno why this is happening...

**Comment by Quinxxz** [comment]
And there's a fog that i can't remove on the settings

**Comment by artdeell** [comment]
show tha aida64 renderer tab

**Comment by Quinxxz** [comment]
I thought my proccesor was snapdragon, i was wrong it was exynos 7 oct

**Comment by ENDERMANYK** [comment]
Currently is nearly impossible to fix due to the limitations of GL4ES

**Comment by Quinxxz** [comment]
There is no problem since i'm gonna get an a20s with a 64 bit processor

**Comment by Danivelgamer90** [comment]
> My processor is an snapdragon, i dunno why this is happening...

Because your processor cannot be snapdragon.

**Comment by TLVIPER** [comment]
When exynos support be in us

**Comment by Birbs-are-cute** [comment]
@TLVIPER i don't know . Open4es supports exynos but u know the line bugs.
