### ISSUE TITLE
Crash when trying to run open 4es shader on mcinabox

### ISSUE THREAD

**Issue by islandslover114514** [Open4Es/Open4Es-Shader-Android#32]
Crash when trying to use open 4es shader with mcinabox
My phone is xperia xz3
if u need crash report i will send you

**Comment by islandslover114514** [comment]
It works fine with pojav luncher... but it works with opengles3.2.

**Comment by ENDERMANYK** [comment]
Update your mcinabox runtime, it should works

**Comment by islandslover114514** [comment]
uh. ok

**Comment by islandslover114514** [comment]
thx fixed
