### ISSUE TITLE
There is a shadow in the cave

### ISSUE THREAD

**Issue by islandslover114514** [Open4Es/Open4Es-Shader-Android#33]
![Screenshot_20210411-082826](https://user-images.githubusercontent.com/74064826/114287190-0a1c3e00-9aa0-11eb-94c9-f913b6ca1843.png)
There is a shadow in cave 
My phone is 
Snapdragon845
Memory is 4gb

**Comment by islandslover114514** [comment]
And it's normal outside
![Uploading Screenshot_20210411-091101.png…]()

**Comment by ENDERMANYK** [comment]
~~should fixed in the new pre-release~~ give a try https://github.com/Open4Es/Open4Es-Shader-Android/releases/tag/1.1.0-Beta
