### ISSUE TITLE
thanks for making the shader, and I want to criticize that this shader exists. there are bugs like this photographed 

### ISSUE THREAD

**Issue by hnsmnndng** [Open4Es/Open4Es-Shader-Android#34]
![Screenshot_2021-04-12-17-59-47-015_net kdt pojavlaunch](https://user-images.githubusercontent.com/82088285/114385058-b3a32280-9bb9-11eb-81c3-ce6a1f4d2685.jpg)

**Comment by ENDERMANYK** [comment]
invalid"final"? can you provide more information?
