### ISSUE TITLE
Weird Lines

### ISSUE THREAD

**Issue by RukaMarine** [Open4Es/Open4Es-Shader-Android#35]
I have tested all shaders and have had a problem with them, there are gray lines covering most blocks including the arm, it kinda looks like vaporwave to me, my phone is a Samsung S9+ and this is what it looks like 
![Screenshot_20210413-011808_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/77972414/114424233-1070fe00-9bf7-11eb-8ab8-53903c0db74e.jpg)
Edit: plus it kinda just looks like a default shader

**Comment by AjGamingPHOfficial** [comment]
![IMG_20210413_102847](https://user-images.githubusercontent.com/65097302/114487968-168ccc00-9c43-11eb-9bf8-e7d5d222fbcd.jpg)
