### ISSUE TITLE
What is this?! 

### ISSUE THREAD

**Issue by CreatManRus** [Open4Es/Open4Es-Shader-Android#39]
![Screenshot_20210417_144300_net.kdt.pojavlaunch.jpg](https://user-images.githubusercontent.com/59284352/115112090-78736b80-9f8c-11eb-924d-818f6f612454.jpg)
I just wanted to play with the shaders, and there's this error

**Comment by CreatManRus** [comment]
I used the Chocapic shaders on 1.16.4

**Comment by ENDERMANYK** [comment]
Read READMD.md
