### ISSUE TITLE
Bug in right click crosser in gun vic modern warfare mod using shader plsss fix this

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#40]
When I right click without shader
![Screenshot_2021-04-19-01-38-48-334_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/115154986-53781900-a0b0-11eb-8f31-8199a274a9cb.jpg)

When I right click with shader
![Screenshot_2021-04-19-01-38-22-795_net kdt pojavlaunch](https://user-images.githubusercontent.com/76839710/115155004-612d9e80-a0b0-11eb-8693-643b6b032909.jpg)

Plsss reply

**Comment by ENDERMANYK** [comment]
nearly impossible, because I don't know how the mod works

**Comment by LANCECRAFT1104** [comment]
Me too
