### ISSUE TITLE
Hey I have a question about this

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#46]
Can u make sun ray not lens ray in the sun?

**Comment by ENDERMANYK** [comment]
Isn't sun ray=lens ray?

**Comment by kedrick021** [comment]
I don't know something like that and water reflection to?

**Comment by ENDERMANYK** [comment]
GL4ES DOESN'T HAVE THE ENOUGH API TO PROVIDE WATER REFLECTION WORKS

**Comment by kedrick021** [comment]
Ah what about the sun len ray? Like when going the sun down  they so many sun ray every derection

**Comment by kedrick021** [comment]
Can I Ash questions again can you add real fog in gl4es? Like real shader fog not distance fog
