### ISSUE TITLE
(sugerencia)

### ISSUE THREAD

**Issue by alex69322** [Open4Es/Open4Es-Shader-Android#47]
Agregar movimiento o texturas mejores al agua

**Comment by ENDERMANYK** [comment]
GL4ES doesn't have to enough API to make the things you said possible

**Comment by Danivelgamer90** [comment]
> GL4ES não tem API suficiente para tornar as coisas que você disse possíveis

But can you add shadow in THE End?

**Comment by ENDERMANYK** [comment]
> > GL4ES não tem API suficiente para tornar as coisas que você disse possíveis
> 
> But can you add shadow in THE End?

isn't that really weird?

**Comment by Danivelgamer90** [comment]
> > > GL4ES não tem API suficiente para tornar as coisas que você disse possíveis
> > 
> > 
> > Mas você pode adicionar sombra no Fim?
> 
> não é estranho?

No, because I know some shaders that have a weak shadow on THE End

**Comment by ENDERMANYK** [comment]
> > > > GL4ES não tem API suficiente para tornar as coisas que você disse possíveis
> > > 
> > > 
> > > Mas você pode adicionar sombra no Fim?
> > 
> > 
> > não é estranho?
> 
> No, because I know some shaders that have a weak shadow on THE End

TBH they're bugs, because most shaders doesn't intended support the end in the first place, and for GL4ES which is... ~~I think not possible~~?

**Comment by Danivelgamer90** [comment]
> > > > > GL4ES não tem API suficiente para tornar as coisas que você disse possíveis
> > > > 
> > > > 
> > > > Mas você pode adicionar sombra no Fim?
> > > 
> > > 
> > > não é estranho?
> > 
> > 
> > Não, porque eu conheço alguns shaders que têm uma sombra fraca no Fim
> 
> TBH eles são bugs, porque a maioria dos shaders não pretendem suportar a extremidade em primeiro lugar, e para GL4ES que é ... ~Eu acho que não é possível~?

Can you add a fog when it rains?

**Comment by ENDERMANYK** [comment]
~~That feature is exists in the pre-releases version~~

**Comment by Danivelgamer90** [comment]
> ~That feature is exists in the pre-releases version~

I have a question

**Comment by Danivelgamer90** [comment]
> > ~That feature is exists in the pre-releases version~
> 
> I have a question

Open4es shaders will continue to work as soon as we can play Minecraft 1.17?

**Comment by ENDERMANYK** [comment]
> > > ~That feature is exists in the pre-releases version~
> > 
> > 
> > I have a question
> 
> Open4es shaders will continue to work as soon as we can play Minecraft 1.17?

if it doesn't work we will make it to work
