### ISSUE TITLE
Open4es Bug 

### ISSUE THREAD

**Issue by shadersarelegit** [Open4Es/Open4Es-Shader-Android#5]
i loaded open4es chocapic on pojav and its not right
there were lines and on open4es seus and open4es kuma,there were also lines and the player shadow is really long.
![20210403_202908](https://user-images.githubusercontent.com/81864051/113480039-e3b93a00-94c4-11eb-9b6f-2c78309d0ceb.jpg)
Processor:Exygon
Phone:Samsung Galaxy S10+
Version:1.16.5

**Comment by heyRyzen** [comment]
maybe for now it fully working on snapdragon soc

**Comment by Kuvimello** [comment]
Um It is not a bug

**Comment by ENDERMANYK** [comment]
Currently Snapdragon device only sorry if it can't works on your device atm

**Comment by Kuvimello** [comment]
I have snapdragon

**Comment by Kuvimello** [comment]
Snapdragon 855

**Comment by ENDERMANYK** [comment]
> Snapdragon 855

Then it should works on your phone

**Comment by Kuvimello** [comment]
It does

**Comment by AjGamingPHOfficial** [comment]
Lmao

**Comment by IMS212** [comment]
doesn't happen for me on iPad Mini 5, via Zink

**Comment by IMS212** [comment]
> Currently Snapdragon device only sorry if it can't works on your device atm

Works for me on iPad Mini 5 via Zink

**Comment by Matryx0207w** [comment]
rove your shader and if it is compatible with snapdragon they did good job
![Screenshot_20210403-122601_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/67695546/113489914-332b4600-9484-11eb-995c-d8ba2f70a2e6.jpg)

**Comment by Matryx0207w** [comment]
a sample of my snapdragon 450 from my mobile

**Comment by Matryx0207w** [comment]
:)

**Comment by Matryx0207w** [comment]
I hope it can be modified in the shaders settings

**Comment by ELXDNT** [comment]
![Screenshot_20210403-200222_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/81885159/113493739-8fa85880-94b8-11eb-9014-47e31ebe4af4.jpg)

._.

**Comment by ENDERMANYK** [comment]
> > Currently Snapdragon device only sorry if it can't works on your device atm
> 
> Works for me on iPad Mini 5 via Zink, however I get random crashes seemingly due to Metal not supporting triangle fans.

Just a bit surprised it works on iOS because i haven't test before

**Comment by shadersarelegit** [comment]
Sad :(

**Comment by shadersarelegit** [comment]
Well ill close this issue then.
Before i close the issue,i wanna ask
@AjGamingPHOfficial How did you get the super duper vanilla shaders?they look really nice

**Comment by AjGamingPHOfficial** [comment]
Google

**Comment by shadersarelegit** [comment]
@AjGamingPHOfficial download link?

**Comment by AjGamingPHOfficial** [comment]
Bruh

**Comment by LANCECRAFT1104** [comment]
Shader is not working on my SNAPDRAGON 450. all features is not working only the sun is working. This shader is only works on all snapdragon processor rigth?

**Comment by LANCECRAFT1104** [comment]
https://github.com/Open4Es/Open4Es-Shader-Android/issues/11

**Comment by Kuvimello** [comment]
Also can you make a BSL version for Open-4es

**Comment by GabudPeople** [comment]
> Currently Snapdragon device only sorry if it can't works on your device atm

But It Work In My Device My Device is Mtk Helio G35 :D

**Comment by ENDERMANYK** [comment]
> > Currently Snapdragon device only sorry if it can't works on your device atm
> 
> But It Work In My Device My Device is Mtk Helio G35 :D

No idea because when i developed the Shader I don't have that much kind of phones to test
