### ISSUE TITLE
open4es sherder is lag than seus sherder

### ISSUE THREAD

**Issue by islandslover114514** [Open4Es/Open4Es-Shader-Android#50]
bruh

**Comment by ENDERMANYK** [comment]
the beta version? ~~but i think it can't laggy than seus shader~~

**Comment by Creeperrrb** [comment]
@ENDERMANYK  it doesn't lag on my device
Shaders off -4fps
Shaders on -3fps
Lol

**Comment by Creeperrrb** [comment]
@ENDERMANYK  it doesn't lag on my device
Shaders off -4fps
Shaders on -3fps
Lol

**Comment by islandslover114514** [comment]
im sorry just unstablb

**Comment by Fordhamgr** [comment]
It will work for 1.12.2 version ?
