### ISSUE TITLE
Night time shadow disability

### ISSUE THREAD

**Issue by Lleeeelll** [Open4Es/Open4Es-Shader-Android#51]
Hello developers, could you please set an automated shadow mapping that turns off in the night time. It looks pretty unrealistic when the shadows look like day time if the light source block is placed.

**Comment by Lleeeelll** [comment]
Also. Can you add water reflection, if no then I understand that it will be super laggy. But give it a try :)

**Comment by ENDERMANYK** [comment]
> Hello developers, could you please set an automated shadow mapping that turns off in the night time. It looks pretty unrealistic when the shadows look like day time if the light source block is placed.

This one got fixed in the new pre-release
https://github.com/Open4Es/Open4Es-Shader-Android/releases/tag/1.1.0-Beta

**Comment by ENDERMANYK** [comment]
> Also. Can you add water reflection, if no then I understand that it will be super laggy. But give it a try :)

GL4ES currently lacks the extension to make water reflection possible

**Comment by Lleeeelll** [comment]
> > Also. Can you add water reflection, if no then I understand that it will be super laggy. But give it a try :)
> 
> GL4ES currently lacks the extension to make water reflection possible

Okay, still on bright side it works Hella smooth thanks.

**Comment by Danivelgamer90** [comment]
> > Também. Você pode adicionar reflexo de água, se não, então eu entendo que será muito lento. Mas dá-lhe uma chance :)
> 
> GL4ES atualmente carece de extensão para tornar possível a reflexão da água

So is it possible to put water with reflection?

**Comment by ENDERMANYK** [comment]
> > > Também. Você pode adicionar reflexo de água, se não, então eu entendo que será muito lento. Mas dá-lhe uma chance :)
> > 
> > 
> > GL4ES atualmente carece de extensão para tornar possível a reflexão da água
> 
> So is it possible to put water with reflection?

no

**Comment by ENDERMANYK** [comment]
unless ptitSeb update the needed extension

**Comment by NarwenD** [comment]
Can I ask what is the file that connected to fog in mc

**Comment by ENDERMANYK** [comment]
> Can I ask what is the file that connected to fog in mc

You can write it in any fragment file, as long as you define the fog

**Comment by NarwenD** [comment]
> > Can I ask what is the file that connected to fog in mc
> 
> You can write it in any fragment file, as long as you define the fog

I mean like uh.. file like gbuffers.**** That connect to the shader fog

**Comment by ENDERMANYK** [comment]
> > > Can I ask what is the file that connected to fog in mc
> > 
> > 
> > You can write it in any fragment file, as long as you define the fog
> 
> I mean like uh.. file like gbuffers.**** That connect to the shader fog

gbuffers default doesn't connect the fog, you need define it, for me I write in gbuffer_terrain.fsh 
![$SR%OK{$L1LCCLJTOZW5BX4](https://user-images.githubusercontent.com/64646658/120881046-eccba200-c600-11eb-9609-4ca49652f5b0.png)

**Comment by NarwenD** [comment]
> > > > Can I ask what is the file that connected to fog in mc
> > > 
> > > 
> > > You can write it in any fragment file, as long as you define the fog
> > 
> > 
> > I mean like uh.. file like gbuffers.**** That connect to the shader fog
> 
> gbuffers default doesn't connect the fog, you need define it, for me I write in gbuffer_terrain.fsh
> ![$SR%OK{$L1LCCLJTOZW5BX4](https://user-images.githubusercontent.com/64646658/120881046-eccba200-c600-11eb-9609-4ca49652f5b0.png)

Ok Thank you very much :)
