### ISSUE TITLE
No shadow in night why?

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#56]
Can you add brightness moon and sun?
Can you add legacy flare in when sun down
Can you add glowing mobs eyes
Can you glowing item like sword and armor
Can you realistic rain and cloud not in resource packs
Can you add pbr

**Comment by ENDERMANYK** [comment]
> Can you add brightness moon and sun?
> Can you add legacy flare in when sun down
> Can you add glowing mobs eyes
> Can you glowing item like sword and armor
> Can you realistic rain and cloud not in resource packs
> Can you add pbr

Do you think GL4ES is equal to PC graphic card? not every thing is available on it

**Comment by kedrick021** [comment]
Can you add mobs glowing eyes plsss
And how to turn on the night shadow shader?

**Comment by ENDERMANYK** [comment]
> Can you add mobs glowing eyes plsss
write it by yourself, because idk how

**Comment by kedrick021** [comment]
Why no shadow in night how to turn on?

**Comment by deathstrande** [comment]
> Can you add mobs glowing eyes plsss
> And how to turn on the night shadow shader?

Bro night time shadow is available in 1.0
