### ISSUE TITLE
Can some one tell me the problem

### ISSUE THREAD

**Issue by senseixen** [Open4Es/Open4Es-Shader-Android#6]
![Screenshot_20210403-225833691](https://user-images.githubusercontent.com/73985410/113482858-1f5b0080-94d3-11eb-9d2c-65bfe14238ba.jpg)
Why?

**Comment by senseixen** [comment]
I try the three shaders but all of them shows that

**Comment by ENDERMANYK** [comment]
What's your phone?

**Comment by senseixen** [comment]
Asus zenfone 5z

**Comment by senseixen** [comment]
I even try it in different type of minecraft like forge optifine ,fabric optifine

**Comment by senseixen** [comment]
![Screenshot_20210403-230205152](https://user-images.githubusercontent.com/73985410/113484314-3e10c580-94da-11eb-8a7b-64492e230327.jpg)
This iis my processor

**Comment by ENDERMANYK** [comment]
Your launcher version?

**Comment by senseixen** [comment]
I'm using latest action do I need to use the release?

**Comment by ENDERMANYK** [comment]
Which render engine you select?

**Comment by senseixen** [comment]
I try them both but it's the same

**Comment by senseixen** [comment]
It still say the same thing

**Comment by ENDERMANYK** [comment]
Try the release version

**Comment by ENDERMANYK** [comment]
I am not sure about this but seem your launcher render engine have the issue

**Comment by senseixen** [comment]
Should I use the release then

**Comment by ENDERMANYK** [comment]
Yes

**Comment by senseixen** [comment]
I work thank you very much

**Comment by LANCECRAFT1104** [comment]
THIS IS MY PROBLEM

**Comment by LANCECRAFT1104** [comment]
> ![Screenshot_20210403-225833691](https://user-images.githubusercontent.com/73985410/113482858-1f5b0080-94d3-11eb-9d2c-65bfe14238ba.jpg)
> Why?

This is my problem

https://github.com/Open4Es/Open4Es-Shader-Android/issues/11
