### ISSUE TITLE
Can you add underwater shadow

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#62]
Can you add underwater shadow not top of water
and glowing eyes mobs much more realistic

I can't add the photo why?

**Comment by kedrick021** [comment]
And the water like chemicals in the sea

**Comment by ENDERMANYK** [comment]
> and glowing eyes mobs much more realistic

already said before idk how to make it

> Can you add underwater shadow not top of water

blame ptitSeb about this

**Comment by kedrick021** [comment]
How about density fog like atmospheric
Make more foggy


O  right your lava become yellow like jelly
And the nether only yellow I don't see any lava anymore
Or torch and lantern

**Comment by kedrick021** [comment]
![Screenshot_2021-06-12-19-14-56-576_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775329-7824d480-cbb9-11eb-9812-be86789e86de.jpg)


![Screenshot_2021-06-12-19-14-35-385_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775332-7b1fc500-cbb9-11eb-8e73-f84b162a9dcf.jpg)


Only glowing eyes it's perfect now

**Comment by Danivelgamer90** [comment]
> ![Screenshot_2021-06-12-19-14-56-576_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775329-7824d480-cbb9-11eb-9812-be86789e86de.jpg)
> 
> ![Screenshot_2021-06-12-19-14-35-385_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775332-7b1fc500-cbb9-11eb-8e73-f84b162a9dcf.jpg)
> 
> Apenas olhos brilhantes é perfeito agora

Can you tell me the names of the mods you are using in this photo?

**Comment by kedrick021** [comment]
7 days to mine

**Comment by kedrick021** [comment]
> > ![Screenshot_2021-06-12-19-14-56-576_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775329-7824d480-cbb9-11eb-9812-be86789e86de.jpg)
> > ![Screenshot_2021-06-12-19-14-35-385_org videolan vlc](https://user-images.githubusercontent.com/76839710/121775332-7b1fc500-cbb9-11eb-8e73-f84b162a9dcf.jpg)
> > Apenas olhos brilhantes é perfeito agora
> 
> Can you tell me the names of the mods you are using in this photo?

7 days to mine

**Comment by Creeperrrb** [comment]
Bruh this is op
