### ISSUE TITLE
Why there is Invisible player model in 3rd person???

### ISSUE THREAD

**Issue by Creeperrrb** [Open4Es/Open4Es-Shader-Android#63]
https://drive.google.com/file/d/14aGwn836tGXdkvr6rbW-yTHnS_m5d9T_/view?usp=drivesdk

Question:
Is there any way to fix lag after optifine??

**Comment by Creeperrrb** [comment]
@ENDERMANYK  plss reply

**Comment by ENDERMANYK** [comment]
For the lag, it's impossible now because the shader added a lot of effects, 3rd person invisible...no idea

**Comment by Creeperrrb** [comment]
@ENDERMANYK why zink Vulcan is not working on mediatek mt 6580,mali 400mp,2gb ram??

**Comment by ENDERMANYK** [comment]
can i know you phone model?

**Comment by Creeperrrb** [comment]
@ENDERMANYK lava iris 821

**Comment by ENDERMANYK** [comment]
idk if you update your android version , but zink need at least android 8

**Comment by Creeperrrb** [comment]
@ENDERMANYK oh I have 6.0 😑😑.btw I'm reviewing all open4es shader on mediatek in my yt channel ok??

**Comment by ENDERMANYK** [comment]
feel free to do that if you link the project

**Comment by Creeperrrb** [comment]
@ENDERMANYK thanks

**Comment by Danivelgamer90** [comment]
> idk if you update your android version , but zink need at least android 8

Mine is Android 8, and Zink still doesn't work on mine.

**Comment by Danivelgamer90** [comment]
> > idk if you update your android version , but zink need at least android 8
> 
> Mine is Android 8, and Zink still doesn't work on mine.

And I have 3GB Ram

**Comment by Creeperrrb** [comment]
@Danivelgamer90 try to install Vulcan renderer.idk if it work

**Comment by Danivelgamer90** [comment]
> @Danivelgamer90 try to install Vulcan renderer.idk if it work

But how do you do that I still don't know

**Comment by Danivelgamer90** [comment]
> @Danivelgamer90 try to install Vulcan renderer.idk if it work

But Vulcan Render ≠ Zink?

**Comment by LANCECRAFT1104** [comment]
> idk if you update your android version , but zink need at least android 8

Doesn't work on my Android 8 CPH1853. All blocks are invisible and also the fonts.

**Comment by ENDERMANYK** [comment]
> > idk if you update your android version , but zink need at least android 8
> 
> Doesn't work on my Android 8 CPH1853. All blocks are invisible and also the fonts.

android 8 is the minimum equipment, you also need Vulkan 1.1 on your GPU
