### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by Minecraftmodster** [Open4Es/Open4Es-Shader-Android#64]
Hi so i like the shader so don't get me wrong but the problem is the lighting every light emitting item is very red and bright so i hope you can change this!

**Comment by jebbyk** [comment]
can you please send some screenshots?

**Comment by Minecraftmodster** [comment]
> can you please send some screenshots?

Okay here just note that this version im on is 1.12.2 
![Screenshot_20210613-121905](https://user-images.githubusercontent.com/81399649/121817984-b960c700-cc41-11eb-91b1-7a92743764fa.png)

**Comment by jebbyk** [comment]
yes please :)
