### ISSUE TITLE
Lightning problem

### ISSUE THREAD

**Issue by romeoga05** [Open4Es/Open4Es-Shader-Android#65]
the light is way too red in beta 2 but i like the shadow and it would be good if you take the light from beta 1

**Comment by jebbyk** [comment]
any screenshots?

**Comment by romeoga05** [comment]
Here

![Uploading Screenshot_2021-06-13-11-24-36-588_com.miui.videoplayer.jpg…]()

**Comment by romeoga05** [comment]
![Screenshot_2021-06-13-11-24-36-588_com miui videoplayer](https://user-images.githubusercontent.com/78824521/121801902-093b9000-cc3a-11eb-925f-b1ce30fada38.jpg)

**Comment by jebbyk** [comment]
thank you
