### ISSUE TITLE
Shader Lines Must Be Fixed

### ISSUE THREAD

**Issue by jumperli** [Open4Es/Open4Es-Shader-Android#66]
I hope this issue will be fixed soon

**Comment by jebbyk** [comment]
any screenshots?

**Comment by ENDERMANYK** [comment]
> any screenshots?

Hmm this problem exists since the first release, it only happened in Mali GPU

**Comment by Creeperrrb** [comment]
Oh I thought only mediatek I have mediatek+ mali GPU.Whem the open4es shader will fully release it's op & improving
Thanks 
@ENDERMANYK &
@ShulkerSakura &
@Craven Tuber
@Aj gaming ph
