### ISSUE TITLE
Is It possible?

### ISSUE THREAD

**Issue by romeoga05** [Open4Es/Open4Es-Shader-Android#67]
Is It possible to make custom Clouds, god Rays, depth of field, Motion Blur, pbr (reflections), Pom, 
Pls comment when a Feature is possible

**Comment by romeoga05** [comment]
Pls make the 

![Uploading Screenshot_2021-06-13-17-12-02-
844_net.kdt.pojavlaunch.jpg…]()

**Comment by deathstrande** [comment]
> Is It possible to make custom Clouds, god Rays, depth of field, Motion Blur, pbr (reflections), Pom,
> Pls comment when a Feature is possible

Please try to understand that these features won't work with all device
