### ISSUE TITLE
Didn't like the world color of new beta update

### ISSUE THREAD

**Issue by deathstrande** [Open4Es/Open4Es-Shader-Android#70]
Hello I didn't like the beta 1, I think that beta 1 is better than beta 2. Beta 2 is like living in a planet which is near sun. Also I was gonna ask you to change the light of beta 1 now beta 2 is fine but would you please add the world color option in next beta update.

Also here is a suggestion if it supports with OpenGL 3
Water transperancy

Hope this suggestion make your shader more great.

**Comment by ENDERMANYK** [comment]
Well what you said makes me confused: you didn't like the beta 1 but think beta 1 is better than beta 2

**Comment by deathstrande** [comment]
> Well what you said makes me confused: you didn't like the beta 1 but think beta 1 is better than beta 2

The issue is that beta 2  world color is like blood red

**Comment by deathstrande** [comment]
Please add world color option just like beta 1

**Comment by deathstrande** [comment]
It will be better

**Comment by ENDERMANYK** [comment]
> > Well what you said makes me confused: you didn't like the beta 1 but think beta 1 is better than beta 2
> 
> The issue is that beta 2 world color is like blood red

Can you provide a screenshot? I only remember nether is red

**Comment by ENDERMANYK** [comment]
> Please add world color option just like beta 1

Due to added the soft shadow that's why temporary disable it

**Comment by deathstrande** [comment]
> > Please add world color option just like beta 1
> 
> Due to added the soft shadow that's why temporary disable it

Oh yes you are right it's fine now

**Comment by deathstrande** [comment]
Thank you so much lol I didn't knew that
