### ISSUE TITLE
Shadow bug

### ISSUE THREAD

**Issue by Tejas-Mahajan** [Open4Es/Open4Es-Shader-Android#71]
When I start playing in my world the shadow of any block is much dark but when I click on my inventory the shadow is low means it's color is light grey so plz fix this bug

**Comment by ENDERMANYK** [comment]
bruh at least provide video screenshot or phone model, how could we fix a bug with 0 information

**Comment by Tejas-Mahajan** [comment]
How to attach the image i have screenshot of bug

**Comment by Tejas-Mahajan** [comment]
So this is the image
![Screenshot_2021-06-17-14-08-34-524_net kdt pojavlaunch](https://user-images.githubusercontent.com/82813922/122364583-825b2000-cf77-11eb-8223-5d383d172490.jpg)
![Screenshot_2021-06-17-14-09-45-490_net kdt pojavlaunch](https://user-images.githubusercontent.com/82813922/122364694-999a0d80-cf77-11eb-8556-8859fbeec7da.jpg)

**Comment by ENDERMANYK** [comment]
bruh that's not bug, that's a feature shadow will change its darkness though the time

**Comment by Tejas-Mahajan** [comment]
Oh

**Comment by Tejas-Mahajan** [comment]
So plz fix the lightning bug that any lightning block or tourch have red color

**Comment by Tejas-Mahajan** [comment]
> bruh that's not bug, that's a feature shadow will change its darkness though the time

But when I click on inventory it's color is changed

**Comment by Tejas-Mahajan** [comment]
So this is the same time 
![Screenshot_2021-06-17-14-48-59-797_net kdt pojavlaunch](https://user-images.githubusercontent.com/82813922/122368854-50e45380-cf7b-11eb-8d6f-039b47c09b15.jpg)
![Screenshot_2021-06-17-14-49-25-410_net kdt pojavlaunch](https://user-images.githubusercontent.com/82813922/122368940-63f72380-cf7b-11eb-9ff5-bfaa2d2a6734.jpg)

**Comment by Tejas-Mahajan** [comment]
When I press on inventory it's color is changed into light color

**Comment by Tejas-Mahajan** [comment]
It is the bug

**Comment by Topline5155** [comment]
![Screenshot_20210622-125028_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/83549358/122870882-721cb980-d358-11eb-9b8a-784a5911a350.jpg)

What??

**Comment by khanhduytran0** [comment]
> ![Screenshot_20210622-125028_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/83549358/122870882-721cb980-d358-11eb-9b8a-784a5911a350.jpg)
> 
> What??

Non-Adreno GPU moment.
