### ISSUE TITLE
Bring back Open4Es-Chocapic, Open4Es-KUMA, and SEUS in beta versions

### ISSUE THREAD

**Issue by LANCECRAFT1104** [Open4Es/Open4Es-Shader-Android#78]
![Screenshot_2021-06-22-18-59-05-82](https://user-images.githubusercontent.com/75970303/122913613-3ac80000-d38c-11eb-8082-1e0153513af6.png)

**Comment by LANCECRAFT1104** [comment]
Somebody please

**Comment by LANCECRAFT1104** [comment]
Hey

**Comment by LANCECRAFT1104** [comment]
How can I change the shadwr color

**Comment by khanhduytran0** [comment]
Bruh, go to `src` folder.
![6AA25D42-37EF-4268-ACC5-2EAA2D58F1F4](https://user-images.githubusercontent.com/40482367/123045805-8c709900-d425-11eb-91ae-c24443edb51a.jpeg)

**Comment by Indoaviator** [comment]
Bugggg
