### ISSUE TITLE
Mtk Processor Bug!

### ISSUE THREAD

**Issue by Smoshii** [Open4Es/Open4Es-Shader-Android#8]
I hope you update shader in mtk processor, thank you!:>

**Comment by GabudPeople** [comment]
> I hope you update shader in mtk processor, thank you!:>

My Device are mtk helio g35 and it work fine

**Comment by Palotops** [comment]
Yo tengo un mtk g90t y me aparece el bug en las sombras :c

**Comment by Palotops** [comment]
I have a mtk g90t and the bug appears in the shadows: c

**Comment by ZhakiThePro** [comment]
I have mtk Helio G80,it work for my device?
