### ISSUE TITLE
Can you give me a code

### ISSUE THREAD

**Issue by kedrick021** [Open4Es/Open4Es-Shader-Android#80]
Can you give me a code for nether world the view code is only for overworld open4es chocapic shader view code

And buggy water code to for chocapic

**Comment by kedrick021** [comment]
![2021-06-27_17-01-58](https://user-images.githubusercontent.com/76839710/123538913-99fd8a00-d769-11eb-953c-0e54d1759637.jpg)


Can you give me code for nether

How to reduce the brightness of white sky?

**Comment by ENDERMANYK** [comment]
wth is code for nether

**Comment by kedrick021** [comment]
Yah only works for overworld not in netherworld

**Comment by ENDERMANYK** [comment]
why would you need it for nether? those are overworld effect only ,also why your picture is so bright, did you modified something?

**Comment by kedrick021** [comment]
No that sec in view code

**Comment by kedrick021** [comment]
And is the modified I reduce the blur and brightness of sky but I can't find why half of sky are white

![Screenshot_2021-06-27-17-27-47-300_org videolan vlc](https://user-images.githubusercontent.com/76839710/123539633-51e06680-d76d-11eb-8a37-0673a4208dbd.jpg)

![Screenshot_2021-06-27-17-28-07-113_org videolan vlc](https://user-images.githubusercontent.com/76839710/123539648-5c026500-d76d-11eb-839c-758ef4dce7f8.jpg)

**Comment by ENDERMANYK** [comment]
why you use old version shader?

**Comment by ENDERMANYK** [comment]
also we even doesn't add blur how is that thing even in the shader?

**Comment by kedrick021** [comment]
That a bloom 
![2021-06-27_17-37-37](https://user-images.githubusercontent.com/76839710/123539878-7852d180-d76e-11eb-92d6-2f9a31098800.jpg)

**Comment by kedrick021** [comment]
That can even effect the light torch and lava

**Comment by ENDERMANYK** [comment]
why don't bloom effect the light and the lava? it should do that

**Comment by kedrick021** [comment]
That v2 not v3 can you tell me why half of sky are white and what code to erase that white in the bottom sky 

![Screenshot_2021-06-27-17-53-17-821_org videolan vlc](https://user-images.githubusercontent.com/76839710/123540240-a1746180-d770-11eb-9cef-46adbd517061.jpg)

**Comment by ENDERMANYK** [comment]
so looks you use the code from the old version then idk, old version doesn't developed by me

**Comment by kedrick021** [comment]
No you use the same for bloom and chromatic aberration effect for v3

**Comment by ENDERMANYK** [comment]
i only developed the V1.1.0 version, since the V1.1.0 version shader is completely rewrite, that sky issue only exists in V1.0.0 version

**Comment by ENDERMANYK** [comment]
also bloom and chromatic aberration doesn't write by me

**Comment by kedrick021** [comment]
Oh! yeah is Jeddy code how can I chat on him?

**Comment by Creeperrrb** [comment]
@kedrick021 u watched crazy mobile channels video right??

**Comment by kedrick021** [comment]
> @kedrick021 u watched crazy mobile channels video right??

Yeah why?

**Comment by Creeperrrb** [comment]
@kedrick021 nothing he just modified the code of old shader open4es chocapic which wasn't developed by @ENDERMANYK

**Comment by kedrick021** [comment]
> @kedrick021 nothing he just modified the code of old shader open4es chocapic which wasn't developed by @ENDERMANYK

Really?

**Comment by Creeperrrb** [comment]
@kedrick021 yes
