### ISSUE TITLE
Question can u add depth of field, motion blur, custom sea lantern color and metal block reflections?? 

### ISSUE THREAD

**Issue by Birbs-are-cute** [Open4Es/Open4Es-Shader-Android#81]
It will me more realistic then

**Comment by Creeperrrb** [comment]
@ENDERMANYK also thanks for commenting in my video I Will upgrade my phone next month

**Comment by ENDERMANYK** [comment]
i think... ~~the sea lantern color is changed..~~

**Comment by Creeperrrb** [comment]
OK lemme check

**Comment by ENDERMANYK** [comment]
others effect was suggested a long ago #18 still have no idea how to do it

**Comment by Creeperrrb** [comment]
Yes sea lantern color is changed. And yeah that guy told about motion blur too but I told to try pbr/metallic reflections like in seus, bsl, nostalgia
