### ISSUE TITLE
Bloom brightness

### ISSUE THREAD

**Issue by Minecraftmodster** [Open4Es/Open4Es-Shader-Android#82]
Hi so i was so excited about the 3rd beta and when i downloaded it I turned on bloom and my brightness was set to moody on minecraft so then i loaded into a world and it was very bright so i turned it off and it wasn't as bright so i hope you can change that

**Comment by deathstrande** [comment]
Idk it looks fine to me

**Comment by Creeperrrb** [comment]
> 
> 
> Hi so i was so excited about the 3rd beta and when i downloaded it I turned on bloom and my brightness was set to moody on minecraft so then i loaded into a world and it was very bright so i turned it off and it wasn't as bright so i hope you can change that

u can turn off bloom from option
