### ISSUE TITLE
Water color and underwater shadow

### ISSUE THREAD

**Issue by deathstrande** [Open4Es/Open4Es-Shader-Android#83]
Your shader is really improving after you added the bloom effect, It's improving. But there is one thing that's stopping this shader to improve, The water. Dry land survival players won't get bothered with this issue. But me, an open ocean survival player is finding it unrealistic. The underwater looks like there are some lights setted on each particle of blocks or say (unrealistic lighting) and also water color suits to bright sky. But I use moderate sky (my optional world color Red: 1.1 | Blue: 1.3 | Green: 1.3). Is there any way you can change the water color in according to world color option?

**Comment by deathstrande** [comment]
Players with their optional colors?

**Comment by ENDERMANYK** [comment]
hmm you mean the underwater is too bright? For the water color change option.. will think about it

**Comment by deathstrande** [comment]
Okay! Hope it would improve it. 👍
