### ISSUE TITLE
Glitchy shadow

### ISSUE THREAD

**Issue by Ivyjunsy** [Open4Es/Open4Es-Shader-Android#87]
I love that you guys made a open4es shader, i really really like it..
Except on the glitchy shadows..
If you move back, the shadow is glitching out..
(As you can see on the picture below)
I dont know why, i thought that maybe the problem is on my video settings, i tried changing my video settings but nothing happend..

Example:
![IMG_20210709_134740](https://user-images.githubusercontent.com/87071336/125029908-e7a8b980-e0bc-11eb-8233-251cb6ee9159.jpg)

Even the beta one is glitching out..
Can you guys maybe fix that in the future updates?

**Comment by MikoLava** [comment]
That's because ur gpu is mali
Mali gpu always has that bug
You need adreno gpu
Or snapdragon processor for that

**Comment by Ivyjunsy** [comment]
So that means im stuck with this?

Ok then..

**Comment by Ivyjunsy** [comment]
Can you guys make it like its good for us, on the next update??

**Comment by ENDERMANYK** [comment]
> Can you guys make it work for us none snapdragon/adreno, on the next update??

nearly impossible, do expect your phone SOC doesn't support the third-party shader*

**Comment by Ivyjunsy** [comment]
Ok....thank you tho
