### ISSUE TITLE
the shader dont work in samsung a50 :(

### ISSUE THREAD

**Issue by ELXDNT** [Open4Es/Open4Es-Shader-Android#9]
:(

**Comment by shadersarelegit** [comment]
Probaly because u need snapdragon processor
I heard from the developer this shader only works on snapdragon proccessors for now.

**Comment by LANCECRAFT1104** [comment]
> Probaly because u need snapdragon processor
> I heard from the developer this shader only works on snapdragon proccessors for now.

It doesn't work on my Snapdragon 450. All features are not working only the sun is working.
