### ISSUE TITLE
Why shadow not working in pc while other features working ??? 

### ISSUE THREAD

**Issue by Creeperrrb** [Open4Es/Open4Es-Shader-Android#91]
Bruh
#

**Comment by Creeperrrb** [comment]
Bruh why

**Comment by khanhduytran0** [comment]
@Creeperrrb you didn't read the shader description? It's made for mobile, not RTX 3090.
![bruh](https://camo.githubusercontent.com/d6b5355a2276e9de998583178fe19a89d0aa58936d4cb59578e53fe8bc879cb9/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3639363131363934323235393631373830322e706e67) ![fruhh](https://camo.githubusercontent.com/30aa99b1002012f92634ee75f2cab1c9fc27623a936f0109ce735e4d1c6df519/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3835353437333237353236353232303632392e706e67)

**Comment by Creeperrrb** [comment]
> @Creeperrrb you didn't read the shader description? It's made for mobile, not RTX 3090.
> ![bruh](https://camo.githubusercontent.com/d6b5355a2276e9de998583178fe19a89d0aa58936d4cb59578e53fe8bc879cb9/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3639363131363934323235393631373830322e706e67) ![fruhh](https://camo.githubusercontent.com/30aa99b1002012f92634ee75f2cab1c9fc27623a936f0109ce735e4d1c6df519/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3835353437333237353236353232303632392e706e67)

Bruh but pojavlauncher and my graphics card both opengl 2.1 Endermanyk toldme to give a try

**Comment by Creeperrrb** [comment]
It should work because other features working like moving plants realistic water underwater caustic

**Comment by khanhduytran0** [comment]
But stills, written for mobile. Mobile device uses OpenGL ES, PC uses OpenGL. OpenGL ≠ OpenGL ES. ~~It would work correctly if you install Windows 11 and sideload PojavLauncher APK and play on your PC.~~

**Comment by Creeperrrb** [comment]
I know it works on myphone perfectly but i just asked for pci got the answer and u should close this issue idk how to close

**Comment by Creeperrrb** [comment]
And also thanks for pojavlauncher

**Comment by khanhduytran0** [comment]
> u should close this issue

I'm not member of this org

> idk how to close

bruh what you've clicked

![_20210713_204611](https://user-images.githubusercontent.com/40482367/125462980-315b7a81-dd7c-4b2e-b685-2791249a104e.jpg)

**Comment by Creeperrrb** [comment]
I meant i lost the button

**Comment by Creeperrrb** [comment]
It was somewhereup

**Comment by Creeperrrb** [comment]
Now disappeared
