### ISSUE TITLE
bugs with light

### ISSUE THREAD

**Issue by VERON0990** [Open4Es/Open4Es-Shader-Android#94]
![Screenshot_2021-07-21-13-35-04-29_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/76649348/126469847-702bfbe5-d1c9-44ea-974b-cad6ef4b8546.jpg)
![Screenshot_2021-07-21-13-35-08-23_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/76649348/126469863-4a898e41-4181-482e-9352-8d3ee304af3a.jpg)

**Comment by Craven-Tuber** [comment]
No but it is normal

**Comment by Craven-Tuber** [comment]
Bug actually

**Comment by Creeperrrb** [comment]
the light fades the shadow this can't be a bug
btw what are u talking about

**Comment by MikoLava** [comment]
There is nothing wrong with it

**Comment by romeoga05** [comment]
What is the Name of the Texture Pack With the cool Sky

**Comment by Dark-Lord-Pro** [comment]
U CAN FIND IT ON planetminecraft.net
It is custom sky texture pack for Java edition
