### ISSUE TITLE
[BUG] Black lines

### ISSUE THREAD

**Issue by ghost** [Open4Es/Open4Es-Shader-Android#95]
When I put the shader, several black lines appear in the game, look at the print
![Screenshot_20210730-162407_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/70015378/127702461-8e568cdc-42a5-4b96-aa29-5bdb382addd6.jpg)
I don't know how to solve this problem

**Comment by Ivyjunsy** [comment]
Due i have the same problem

**Comment by Ivyjunsy** [comment]
The problem is that we have the mali gpu that's why we can't properly use the shader, this shader is only for phone that have snapdragon gpu....

And they said that they can't fix that problem, so we have to stick with it....
No other choice

**Comment by Creeperrrb** [comment]
@DayvidPlays  & @Ivyjunsy 
this bug is nott a bug for shader. u know java edition is  a  powerful game u  need a perfect prossecor for runnning thiis shader. if u usesnapdragon prossecoor thee bug won't apear

**Comment by Ivyjunsy** [comment]
Yeah i know that's why i explained it to him.... Can't you see???

**Comment by romeoga05** [comment]
When you Install pojav Launcher Zink there a No black lines i Tested it

**Comment by Ivyjunsy** [comment]
The line is more thicker when you use the zink Pojavlauncher.. i tested it as well...

**Comment by Ivyjunsy** [comment]
> When you Install pojav Launcher Zink there a No black lines i Tested it

Is your phone's gpu mali anyway??

**Comment by Marknelson29** [comment]
This is so annoying I'm playing Minecraft too may GPU Malli too
