### ISSUE TITLE
The shadow glitches are getting fixed now...however

### ISSUE THREAD

**Issue by MrProPeeveepee** [Open4Es/Open4Es-Shader-Android#99]
Hello,I'm here to give some issues for the shadow,I'm using a mediatek device and a mali gpu,all I wanna give is the lining shadow glitches are still there in version beta5,but its less visible now,however,the performance were getting poorly now I barely reach 30 fps...but I am really satisfied that the shadow glitches are less visible now..like i said,the performance is getting down now I hope you fix it...or maybe the shadow glitches,its getting better now theres still chances you can fix it,or keep it like that just fix the performance problem, that's all for now,have a good day and maybe take a rest first before fixing it...again,have a good day:D(sorry for bad eng)

**Comment by MrProPeeveepee** [comment]
@ENDERMANYK @jebbyk

**Comment by BurstingCreeper** [comment]
@MrProPeeveepee  because pojavlauncher has vgpu now no more gl4es vgpu supports opengl 3.2 so it should fix

**Comment by MrProPeeveepee** [comment]
@BurstingCreeper wdym by vgpu?I used the vgpu and zink ver but it makes the glitch worse,also,the shader now is very laggy..bruh idk I'm not good at english

**Comment by BurstingCreeper** [comment]
@MrProPeeveepee u need vgpu or zink version of pojav to run that shader u can't run it in normal pojav

**Comment by BurstingCreeper** [comment]
yes but u need either zink or vgpu and zink or vgpu should be selecte on renderer option in pojaauncher
